export const HOBBY_PLAN_SCREENSHOT_COUNT = 5000;
export const PRO_PLAN_FLAT_PRICE = 30;
export const PRO_PLAN_SCREENSHOT_COUNT = 15000;
export const ADDITIONAL_SCREENSHOT_PRICE = 0.0025;
export const GITHUB_SSO_PRICE = 50;
