export const ARGOS_HOBBY_SCREENSHOT_COUNT = 5_000;
export const ARGOS_PRO_FLAT_PRICE = 100;
export const ARGOS_PRO_FLAT_SCREENSHOT_COUNT = 35_000;
export const ARGOS_SCREENSHOT_PRICE = 0.004;
export const ARGOS_STORYBOOK_SCREENSHOT_PRICE = 0.0015;
export const GITHUB_SSO_PRICE = 50;
