export const PRO_PLAN_BASE_PRICE = 100;
export const HOBBY_PLAN_SCREENSHOT_COUNT = 5000;
export const PRO_PLAN_SCREENSHOT_COUNT = 15000;
export const ADDITIONAL_SCREENSHOT_PRICE = 0.004;
export const GITHUB_SSO_PRICE = 50;
