name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies and launch Cypress tests
        uses: cypress-io/github-action@v6
        env:
          ARGOS_PREVIEW_BASE_URL: ${{ github.event_name == 'pull_request' && format('https://argos-website-git-{0}-argos-ci.vercel.app', github.head_ref) || 'https://argos-ci.com' }}
        with:
          build: pnpm run build
          start: pnpm run start
